application: bb-classic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /.*
  script: bb.app
  secure: always

- url: /(genkeys|addkey)
  script: crypto.application
  login: admin
  secure: always

libraries:
- name: webapp2
  version: latest

- name: pycrypto
  version: latest

- name: jinja2
  version: latest

skip_files:
- ^(.*/)?\.xml
- ^(.*/)?\.egg
- ^(.*/)?\.egg-info
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?api/.*
- ^(.*/)?tmp/.*
- ^(.*/)?app.db
- ^(.*/)?app.db.backup
- ^(.*/)?app.db.filestub
